#docker-compose up 
version: '3'
services:
    contenedor_mysql_javier:
      image: mysql:8
      restart: always
      environment:
        MYSQL_DATABASE:      wordpressproyecto
        MYSQL_USER:          javier
        MYSQL_ROOT_PASSWORD: Alisal2022
        MYSQL_PASSWORD:      Alisal2022
        #MYSQL_RANDOM_ROOT_PASSWORD: '1'
      volumes:
        - mysql_data:/var/lib/mysql      
      networks:
        - red-interna
    contenedor_wordpress_javier:
        depends_on:
            - contenedor_mysql_javier
        image: wordpress:latest
        ports:
            - "8005:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST:     contenedor_mysql_javier:3306
            WORDPRESS_DB_USER:     javier
            WORDPRESS_DB_PASSWORD: Alisal2022
            WORDPRESS_DB_NAME:     wordpressproyecto
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - red-interna
            - red-publica        
volumes:
  mysql_data: {}
  wordpress_data: {}
#Se crean dos redes. Una especifica entre el wp y el mysql
# y otra publica para el wordpress
networks: 
  red-interna:
  red-publica:          
